### ISSUE TITLE
Illegal tag for StateGraph2 v2.0.3

### ISSUE THREAD

**Issue by modelica-trac-importer** [HansOlsson/Modelica_StateGraph2#4]
**Reported by dietmarw on 12 Apr 2016 12:58 UTC**
I was just about to sync the GitHub mirror with the latest release of the StateGraph2 library when I noticed that it contains the non-defined `versionBuild=0`. This should be changed to `versionBuild=1` and then re-tagged. Ideally simply `v2.0.3` (i.e., no +build since that really is not necessary and just adds noise to the name).

The old tag should simply be removed. 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1983

**Comment by beutlich** [comment]
Neither v2.0.3 nor v2.0.4 (the latest version distributed by Dymola 2020) are available from the [releases page](https://github.com/HansOlsson/Modelica_StateGraph2/releases).

**Comment by HansOlsson** [comment]
> 
> 
> Neither v2.0.3 nor v2.0.4 (the latest version distributed by Dymola 2020) are available from the [releases page](https://github.com/HansOlsson/Modelica_StateGraph2/releases).

Oops missed that. v2.0.4 is now published there. I will skip adding 2.0.3 to release page for now.
