### ISSUE TITLE
OpenModelica fails with StateGraph2.Transition

### ISSUE THREAD

**Issue by AHaumer** [HansOlsson/Modelica_StateGraph2#8]
I filed a bug report at OpenModelica, getting the comment from Adrian Pop:
The error message in the new front-end is correct. The line reads:
{{{#!mo
Connections.branch(inPort[i].node, node);
}}}
which is not according to the Modelica Specification because {{{node}}} is
not of the form {{{connectorName.overconstrainedRecord}}}. One would need
to put the node inside a connector and use that to make it correct. Or the
Modelica spec needs changing.

**Comment by adrpo** [comment]
Now OpenModelica new front-end allows this non-standard usage of the overconstrained record directly instead of being part of a connector. The questions are now:
- do we fix the library? Is that possible?
- do we change the ModelicaSpec to allow the non-standard usage in this library?
